### ISSUE TITLE
flex 布局

### ISSUE THREAD

**Issue by oakland** [oakland/tecblog#109]
flex 布局不复杂，说下 flex-grow, flex-shrink, flex-basis 这几个属性的特殊值，还有意义。
通常而言，如果不希望扩展或者缩小的时候，flex-grow 和 flex-shrink 就设置为 0。
flex-grow 的真正意义是，多余出来的空间以何种比例分配。
假设有如下 html 代码：
```html
<div class="container">
  <div class="left">left</div>
  <div class="right">right</div>
</div>
```

CSS 代码如下：
```css
.container {
  display: flex;
  flex-direction: row;
  align-items: flex-start;
  justify-content: space-between;
}
.left {
  flex: 2 0 300px;
  height: 100px;
  background-color: orange;
}
.right {
  flex: 1 0 800px;
  height: 50px;
  background-color: yellowgreen;
}
```
当 container
