### ISSUE TITLE
Gitlab 相关

### ISSUE THREAD

**Issue by oakland** [oakland/tecblog#320]
### gitlab-runner 并发运行多个 pipeline
git-runner 默认的配置只会运行一个 pipeline，例如一个同事在 dev 更新了，dev 开始打包。在 dev 打包还没有完成的时候，另一个同事在 staging 更新了代码，那么 staging 的打包就会排队等在 dev 打包之后进行。如果想要同时运行多个 pipeline，例如这个时候 staging 也可以立即打包，就需要修改一下配置文件。
- 通过 `ps -ef | grep -i gitlab` 命令查看配置文件的地址，`/etc/gitlab-runner/config.toml`
- 通过 vim 打开 `config.toml` 文件，将 `concunrrent` 配置从 1 修改成 2，或者任何你想要的数字，但是应该是要少于计算机的核数。
- 通过 `:wq` 保存文件，然后执行 `gitlab-runner restart` 命令重启服务
- 就可以了

这个 .toml 的配置文件还有很多高级的配置，但是我都没有用到，可以参考这个[文档](https://docs.gitlab.com/runner/configuration/advanced-configuration.html?source=post_page-----a5dcc092cee7--------------------------------)

关于如何监控 gitlab-runner 的运行状态，还可以参考这篇 [文章](https://faun.pub/maximize-your-gitlab-runner-power-with-ci-cd-concurrent-pipelines-a5dcc092cee7)

### 如何让 pipeline 同时执行多个 stage
在比较简单的情况下，`.gitlab-ci.yml` 文件的所有 stages 都是串行的，但是有些可以并行。例如打包之后，需要同时 `rsync` 到多个测试机上，这个时候只需要把他们的 stage 修改成同一个就行了。例如：
```
stages:
  - install
  - build
  - sync

install:
  stage: install
  cache:
    paths:
      - node_modules/
  script:
    - echo "Installing packages"
    - cd /opt/fe/my-project
    - git add .
    - git stash
    - git checkout dev
    - git pull origin dev
    - npm install
  rules:
    - if: '$CI_COMMIT_BRANCH == "dev"'
      changes:
        - package-lock.json
        - package.json
  tags:
    - xxx

build:
  stage: build
  script:
    - echo "Building"
    - cd /opt/fe/my-project
    - git add .
    - git stash
    - git checkout dev
    - git pull origin dev
    - npm run deploy:prod
    - echo "Success!"
  rules:
    - if: '$CI_COMMIT_BRANCH == "dev"'
    - if: '$CI_DEPLOY_FREEZE == null'
  tags:
    - xxx

syncToServer1:
  stage: sync
  script:
    - echo "Sync to server 1"
    - cd /opt/fe/my-project
    - rsync --delete -rzh ./dist/ root@192.168.100.100:/path/to/project
    - echo "Success!"
  rules:
    - if: '$CI_COMMIT_BRANCH == "dev"'
  tags:
    - xxx

syncToServer2:
  stage: sync
  script:
    - echo "Sync to server 1"
    - cd /opt/fe/my-project
    - rsync --delete -rzh ./dist/ root@192.168.100.101:/path/to/project
    - echo "Success!"
  rules:
    - if: '$CI_COMMIT_BRANCH == "dev"'
  tags:
    - xxx
```
在上面的配置中，syncToServer1 和 syncToServer2 就会同时并发执行。
