### ISSUE TITLE
CSS 常见问题及解决方案

### ISSUE THREAD

**Issue by oakland** [oakland/tecblog#74]
很多常见的 CSS 规则，我常常去百度一下应用，虽然记忆没有太多的意义，但是如果不百度的话还是会节约一些时间。所以就开了这个 issue 去记录一下常见的一些 CSS 规则，时不时看一看能复习一下。

### 强制不换行
有时候我们希望一个 DOM 元素的内容是由内部的文字自动撑宽的，并不是限定死的，所以我们不会给这个 DOM 元素设置宽度，但是却发现这个 DOM 元素内部的文字内容过多的时候文字会自动换行。为了强制文字不换行，我们可以用下面的代码：

```css
.targetElement { white-space: nowrap; }
```
